"""criar tabela de usuarios

Revision ID: b825c001d57b
Revises: 307a2614cc82
"""

from alembic import op
import sqlalchemy as sa


# Identificadores utilizados pelo Alembic.
revision = "b825c001d57b"
down_revision = "307a2614cc82"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "usuarios",

        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),

        sa.Column(
            "nome",
            sa.String(length=150),
            nullable=False,
        ),

        sa.Column(
            "login",
            sa.String(length=80),
            nullable=False,
        ),

        sa.Column(
            "email",
            sa.String(length=150),
            nullable=True,
        ),

        sa.Column(
            "senha_hash",
            sa.Text(),
            nullable=False,
        ),

        sa.Column(
            "perfil",
            sa.String(length=20),
            nullable=False,
        ),

        sa.Column(
            "ativo",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),

        sa.Column(
            "deve_trocar_senha",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),

        sa.Column(
            "ultimo_acesso_em",
            sa.DateTime(timezone=True),
            nullable=True,
        ),

        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),

        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),

        sa.CheckConstraint(
            (
                "perfil IN "
                "('ADMIN', 'DIRETOR', 'SETOR', 'AUDITOR')"
            ),
            name="ck_usuarios_perfil",
        ),

        sa.PrimaryKeyConstraint(
            "id",
        ),

        schema="semed",
    )

    op.create_index(
        "ix_semed_usuarios_login",
        "usuarios",
        ["login"],
        unique=True,
        schema="semed",
    )

    op.create_index(
        "ix_semed_usuarios_email",
        "usuarios",
        ["email"],
        unique=True,
        schema="semed",
    )


def downgrade():
    op.drop_index(
        "ix_semed_usuarios_email",
        table_name="usuarios",
        schema="semed",
    )

    op.drop_index(
        "ix_semed_usuarios_login",
        table_name="usuarios",
        schema="semed",
    )

    op.drop_table(
        "usuarios",
        schema="semed",
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rotas_geral', schema='semed') as batch_op:
        batch_op.drop_index('idx_rotas_geral_geom', postgresql_using='gist')
        batch_op.alter_column('geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
        batch_op.alter_column('pontos_notaveis',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('requisicoes', schema='semed') as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('escolas', schema='semed') as batch_op:
        batch_op.add_column(sa.Column('bairro_povoado_assentamento', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fid', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_de_escola', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('numero_de_porta', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('turno', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_escolas_geom', postgresql_using='gist')
        batch_op.alter_column('geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=31984, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('telefone')
        batch_op.drop_column('diretor')

    with op.batch_alter_table('usuarios', schema='semed') as batch_op:
        batch_op.drop_index(batch_op.f('ix_semed_usuarios_login'))
        batch_op.drop_index(batch_op.f('ix_semed_usuarios_email'))

    op.drop_table('usuarios', schema='semed')
    # ### end Alembic commands ###
